// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_List.Infrastructure.Data;

namespace To_Do_List.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("To_Do_List.Domain.Entities.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR (50)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 7, 24, 13, 28, 48, 675, DateTimeKind.Local).AddTicks(2434),
                            Estado = false,
                            ModificationDate = new DateTime(2022, 7, 24, 13, 28, 48, 680, DateTimeKind.Local).AddTicks(5452),
                            Nombre = "Aprender C#",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(1980),
                            Estado = true,
                            ModificationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2010),
                            Nombre = "Aprender HTML",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2023),
                            Estado = true,
                            ModificationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2027),
                            Nombre = "Aprender CSS",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2035),
                            Estado = true,
                            ModificationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2040),
                            Nombre = "Aprender JS",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2046),
                            Estado = true,
                            ModificationDate = new DateTime(2022, 7, 24, 13, 28, 48, 681, DateTimeKind.Local).AddTicks(2050),
                            Nombre = "Aprender React",
                            SoftDelete = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
